# Generated by Django 2.2.7 on 2019-11-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_auto_20191120_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.Series'),
        ),
    ]
