# Generated by Django 2.2.7 on 2019-11-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_season_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeURL', models.CharField(max_length=200)),
                ('episodeName', models.CharField(max_length=200)),
                ('airedSeason', models.IntegerField()),
                ('episodeNumber', models.IntegerField()),
                ('airdate', models.DateField()),
                ('airtime', models.TimeField()),
                ('runtime', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvshows.Image')),
            ],
        ),
    ]
