# Generated by Django 2.2.7 on 2019-11-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0006_auto_20191120_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='season',
            name='webChannel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
