# Generated by Django 2.2.7 on 2019-11-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0008_auto_20191120_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='url',
        ),
        migrations.RemoveField(
            model_name='series',
            name='seriesURL',
        ),
    ]
