# Generated by Django 2.2.7 on 2019-11-29 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0009_auto_20191121_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tvshows.Image'),
        ),
    ]
