# Generated by Django 2.2.7 on 2019-12-02 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0010_auto_20191129_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tvshows.Image'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tvshows.Image'),
        ),
    ]
