# Generated by Django 2.2.7 on 2019-12-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0011_auto_20191202_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='episodeURL',
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tvshows.Series'),
        ),
    ]
